import { describe, it, expect } from 'vitest';

import agent from '../assets/agents/clippy/agent.mjs';
import hd from '../assets/agents/clippy/map@3x.mjs';
import map from '../assets/agents/clippy/map.mjs';

interface Agent { framesize: [number, number]; animations: Record<string, { frames: Array<{ images: Array<[number, number]> }> }> }
interface Hd { scale: number; stripHeight: number; strips: string[] }

const a = agent as Agent;
const h = hd as Hd;

/** PNG dimensions straight from the IHDR chunk (no full decode). */
function pngSize(dataUri: string): [number, number] {
  const buf = Buffer.from(dataUri.slice(dataUri.indexOf(',') + 1), 'base64');
  expect(buf.subarray(1, 4).toString('ascii')).toBe('PNG');
  expect(buf.subarray(12, 16).toString('ascii')).toBe('IHDR');
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

describe('map@3x.mjs (xBRZ sheet generated by scripts/upscale-sprite.mjs)', () => {
  const [fw, fh] = a.framesize;
  const [w1, h1] = pngSize(map as string);

  it('strips tile the 1x sheet exactly at the stated scale', () => {
    expect(h.scale).toBeGreaterThanOrEqual(2);
    expect(h.stripHeight).toBe(fh * h.scale);
    expect(h.strips.length * fh).toBe(h1);
    for (const s of h.strips) expect(pngSize(s)).toEqual([w1 * h.scale, h.stripHeight]);
  });

  it('every frame offset × scale lies inside its strip', () => {
    let frames = 0;
    for (const anim of Object.values(a.animations)) {
      for (const frame of anim.frames) {
        for (const [x, y] of frame.images ?? []) { // some frames are image-less (sound/branch only)
          frames++;
          expect(y % fh).toBe(0); // a frame never straddles two strips
          expect(x * h.scale + fw * h.scale).toBeLessThanOrEqual(w1 * h.scale);
          expect(Math.floor((y * h.scale) / h.stripHeight)).toBeLessThan(h.strips.length);
        }
      }
    }
    expect(frames).toBeGreaterThan(1000);
  });
});
